### PR TITLE
Logic fix

### PR DESCRIPTION
**Pull request by streamer45**
Just fixing the operator which should become an OR in the positive case.

### CODE REVIEW

**Comment by AdamCraven** [comment]
Many thanks @streamer45 . Feel free to add yourself as a contributor to the principle if you like: https://principles.dev/documentation/#contributors 

If not I'll merge and close in tomorrow

**Comment by MattDenB** [comment]
Darn, someone beat me to it!

**Comment by AdamCraven** [comment]
@MattDenB another eagle eye 👍

**Comment by AdamCraven** [comment]
@streamer45 Merged and on the website https://principles.dev/p/logic-should-be-in-the-positive/

If you want to change it from *streamer45* on the website to your name/profile, all you need to do it log in with github. You'll also get a special *founding badge* on your profile for being a contributor in the alpha period.

**Pull request merged**
